spring: 
  application: 
    name: city-service 
server: 
  port: 9080
info:
  description: City-Service-Eureka App
  name: City Service Assignment

eureka: 
  client: 
    serviceUrl: 
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} 
  instance: 
    hostname: localhost 
    preferIpAddress: true
    status-page-url-path: http://${eureka.instance.hostname}:${server.port}/cities 
    health-check-url: http://${eureka.instance.hostname}:${server.port}/health 
    home-page-url: http://${eureka.instance.hostname}:${server.port}/
  register-with-eureka: true
  fetch-registry: false
